version: '3'
services:
  web:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - '3000:3000'
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app
    environment:
      - REACT_APP_GOOGLE_MAP_API_KEY=${REACT_APP_GOOGLE_MAP_API_KEY}
      - REACT_APP_EMAIL_SERVICE_ID=${REACT_APP_EMAIL_SERVICE_ID}
      - REACT_APP_EMAIL_TEMPLATE_ID=${REACT_APP_EMAIL_TEMPLATE_ID}
      - REACT_APP_EMAIL_PUBLIC_KEY=${REACT_APP_EMAIL_PUBLIC_KEY}
      
  
    
    
  
    
      