version: '3'
services:
  web:
    image: "waadmin/portfolio-front"
    ports:
      - '80:80'
    environment:
      - REACT_APP_GOOGLE_MAP_API_KEY=$REACT_APP_GOOGLE_MAP_API_KEY     
      - REACT_APP_EMAIL_SERVICE_ID=$REACT_APP_EMAIL_SERVICE_ID     
      - REACT_APP_EMAIL_TEMPLATE_ID=$REACT_APP_EMAIL_TEMPLATE_ID   
      - REACT_APP_EMAIL_PUBLIC_KEY=$REACT_APP_EMAIL_PUBLIC_KEY
      